# Guide deploiement permanent sur Render.com (gratuit)
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  DEPLOYER PARIPOTES EN LIGNE (GRATUIT)" -ForegroundColor Green
Write-Host "  Lien permanent : https://paripotes.onrender.com" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Etape 1 — Compte GitHub (gratuit)"
Write-Host "  -> https://github.com/signup"
Write-Host ""
Write-Host "Etape 2 — Creer un repo"
Write-Host "  -> github.com/new"
Write-Host "  -> Nom : paripotes"
Write-Host "  -> Upload les fichiers du dossier server/ (sans node_modules ni .env)"
Write-Host ""
Write-Host "Etape 3 — Compte Render (gratuit)"
Write-Host "  -> https://render.com/register"
Write-Host "  -> Connecte ton GitHub"
Write-Host ""
Write-Host "Etape 4 — Nouveau Web Service"
Write-Host "  -> New + -> Web Service -> choisis le repo paripotes"
Write-Host "  -> Root Directory : (vide ou server si tout est a la racine)"
Write-Host "  -> Build Command  : npm install"
Write-Host "  -> Start Command  : npm start"
Write-Host "  -> Plan : Free"
Write-Host ""
Write-Host "Etape 5 — Variables d'environnement (Environment)"
Write-Host "  Ajoute ces variables (copie depuis ton .env local) :"
Write-Host "    SMTP_HOST = smtp.gmail.com"
Write-Host "    SMTP_PORT = 587"
Write-Host "    SMTP_USER = tryhardd71@gmail.com"
Write-Host "    SMTP_PASS = (ton mot de passe d'application)"
Write-Host "    SMTP_FROM = PariPotes <tryhardd71@gmail.com>"
Write-Host ""
Write-Host "Etape 6 — Deploy"
Write-Host "  -> Clique Create Web Service"
Write-Host "  -> Attends 2-3 min"
Write-Host "  -> Ton lien permanent : https://paripotes.onrender.com"
Write-Host ""
Write-Host "Note : sur le plan gratuit, le site 'dort' apres 15 min sans visite"
Write-Host "       (premiere visite = 30 sec de chargement, puis rapide)"
Write-Host ""